name: Dain Review CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8.0.345+1'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build
      shell: bash

    - name: Run tests
      run: ./gradlew test

    - name: Package application
      run: ./gradlew assemble

    - uses: actions/upload-artifact@v2
      with:
        name: packaged-app
        path: build/libs/*.jar
