name: Dain Review CI/CD

on:
  push:
    branches:
    - main
env:
  S3_BUCKET_NAME: fastcampers-final
  RESOURCE_PATH: ./src/main/resources/application.properties <- 참고 블로그에선 application.yml 로 진행하였는데...
  CODE_DEPLOY_APPLICATION_NAME: fastcampers-final-codeDeploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: fastcampers-final-group


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Set Environment Variables
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
        echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> $GITHUB_ENV
        echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> $GITHUB_ENV
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    - name: Package application
      run: ./gradlew assemble

    - name: Make zip file
      run: zip -r ./$GITHUB_SHA.zip .

      # - uses: actions/upload-artifact@v2
   #   with:
   #     name: packaged-app
   #     path: build/libs/*.jar

    - name: Upload to S3
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        run: aws s3 cp ./$GITHUB_SHA.zip s3://fastcampers-final/$GITHUB_SHA.zip
             
             
    - name: Deploy to EC2 using CodeDeploy
      run: |
        aws deploy create-deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip

